### ISSUE TITLE
comment section?

### ISSUE THREAD

**Issue by etharion** [MrEliasen/BDO-Gear-Calculator#1]
Hey du!

Er forholdsvis ny til GitHub ;) men faldt lige over din BDO calculator. LOVE IT <3!

men lagde lige mærke til på grunil armor: set effects
Armor + shoes: Max HP +150
Helmet + Gloves:  All ap +5

Ellers tak igen for deling af din calculator ;)
Hilsen Rasmus.

**Comment by MrEliasen** [comment]
Hey!
det skulle være rettet nu :) (det var en visuel fejl)
Har lige tilføjet gems i 0.3.0, enjoy!
